baseURL = "http://sundsvallsstigcyklister.se/"
languageCode = "sv-SE"
title = "Sundsvalls Stigcyklister"
theme = "hugo-now-ui"

MetaDataFormat = "yaml"
DefaultContentLanguage = "sv"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/images/favicon.ico"
  appicon = "/images/apple-icon.png"
  background = "/img/bg11.jpg"
  tint = "ssc"
  custom_css = []
  custom_js = []
  date_format = "Mon, Jan 2, 2006"
  description = "Sundsvalls Stigcyklister"

  # options for highlight.js (version, additional languages, and theme)
  highlightjsVersion = "9.10.0"
  highlightCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml"]
  highlightjsTheme = "github"

[menu]

  [[menu.main]]
    identifier = "cykla"
    name = "Cykla i Sundsvall"
    url = "/cykla/"
    weight = 1
  [[menu.main]]
    name = "Översikt"
    url = "/cykla/"
    weight = 1
    parent = "cykla"
  [[menu.main]]
    name = "Kliss"
    url = "/cykla/kliss/"
    weight = 2
    parent = "cykla"

  [[menu.main]]
    identifier = "about"
    name = "Om Oss"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "medlem"
    name = "Bli Medlem"
    url = "/medlem/"
    weight = 3
