baseURL = "https://www.sundsvallsstigcyklister.se"
languageCode = "sv-SE"
title = "Sundsvalls Stigcyklister"
theme = "hugo-now-ui"

MetaDataFormat = "yaml"
DefaultContentLanguage = "sv"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/images/favicon.ico"
  appicon = "/images/apple-icon.png"
  background = "/img/bg11.jpg"
  tint = "ssc"
  custom_css = []
  custom_js = []
  date_format = "Mon, Jan 2, 2006"
  description = "Sundsvalls Stigcyklister"

[menu]

  [[menu.main]]
    identifier = "cykla"
    name = "Cykla"
    url = "/cykla/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "Om Oss"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "medlem"
    name = "Medlemskap"
    url = "/medlem/"
    weight = 3
